services:
  reverse-proxy:
    image: nginx:1.29.3-alpine
    restart: always
    # network_mode: host # same as host to access other ports by other compose
    ports:
      - "192.168.1.253:80:80" # If multiple eth binded to different addresses, filter this way
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro